### ISSUE TITLE
Plotting meta model

### ISSUE THREAD

**Issue by troettge** [many-speech-analyses/many_analyses#159]
1. the extreme values are back. I think they disappeared due to the duplicate model names
![image](https://user-images.githubusercontent.com/13022447/189514506-7fe46636-2c60-4fcf-a042-8f478c56a8ae.png)

2. plotting shrunk and unshrunk estimates is confusing as fuck due to the nature of skrinkage (so the estimate and the shrunken estimate will be at completely different points due to the weighting of variance). I propose just simply plotting the raw estimate alongside 95% CIs. Like so:
![image](https://user-images.githubusercontent.com/13022447/189514867-71622a91-1fe0-4563-b582-a51f6efe0201.png)

This is the real deal because you see the estimates range from 1 to -1. This is the more powerful plot IMO and communicates a powerful message. 

Decisions: 

- [ ] which one do you prefer (or do you have alternative suggestions, answer with :kiss: for shrunk plot, answer with :skull: for raw data plot)
- [ ] picking raw data plot, I have now just used +- 1.96*SE as the cut off point for compelling effects. Alternative suggestions? Maybe get rid of altogether? We originally had a column in the coding scheme with "found_effect". Stefano did not code that. We could use that column to color code the effects that teams considered as rejecting null. However, the plot displays not models but typicality effects (two data points for the same model for atypical and medium), so that does not match nicely either. What do you think?
- [ ] color code. I cannot really use the color code from the other plots because it is viridis_d and they are not great in expressing a binary color contrast (on white background anyways). Alternative suggestions?

**Comment by jvcasillas** [comment]
💀

Re point 2: I think I would prefer not to color code based on whether or not they stated finding an effect for the reasons you specify (they weren't all necessarily looking for the same thing). I don't want to give anybody the impression we are "putting words in their mouths" or whatever. We can keep the shrunken estimates plot in the supp. materials. 

Re point 3: I don't care too much about the colors (in reality I like purple and orange, you already know why). I just think they look a bit fugly with such small points. You generally have good aesthetic taste so I'm ok with whatever you think is good. IMO you can never go wrong with good old #cc0033. 🤷🏼‍♀️

**Comment by troettge** [comment]
Re 3: I could just remove the three different categories and code those that do not overlap with zero as your good old red ;)

**Comment by troettge** [comment]
But we should definitely talk about how many times teams called a finding significant, right? so that part of the table (found_effect) should be filled out and reported?

**Comment by stefanocoretta** [comment]
> Re 3: I could just remove the three different categories and code those that do not overlap with zero as your good old red ;)

I would keep the three categories. As for colour, your choice.

**Comment by stefanocoretta** [comment]
> But we should definitely talk about how many times teams called a finding significant, right? so that part of the table (found_effect) should be filled out and reported?

Yes, I would add a statement about how many reported there to be a significant effect, whatever that effect was (so as a separate remark, rather than part of that plot). I had not coded for that so if one of you could do that, that would be great (I don't have the time alas to do that).

**Comment by stefanocoretta** [comment]
> * [ ]  which one do you prefer (or do you have alternative suggestions, answer with 💋 for shrunk plot, answer with 💀 for raw data plot)

I would include both. They are short and wide so they fit into a nice box on a page.

**Comment by troettge** [comment]
I really feel like plotting both is silly, but I gave it another try to plot them together, yay or nay?

![image](https://user-images.githubusercontent.com/13022447/189682785-2c58bbeb-5921-499b-a05b-6b5cc3117f4a.png)

**Comment by stefanocoretta** [comment]
It's too busy. I think it makes perfect sense to have both, separately, which is not silly at all.

**Comment by troettge** [comment]
Can you be more specific what you mean with too busy? I don't think it is too busy. I can take out the smallest and largest effect annotation. I think it does a good job in showing the large variability of raw estimates. I am worried that people cannot interpret shrunken estimates out of context (in a dedicated plot). What does Dr. Casillas think? @jvcasillas

**Comment by stefanocoretta** [comment]
Not much I can add. There's too much in not enough space. Can you perhaps try to dodge the estimates with bars so that you have each model with original and shrunk side by side rather than overlapped? As it is now, it's difficult to read.

**Comment by troettge** [comment]
That would literally make the plot twice as busy by having over 300 lines along the x-axis. I don't think the non-extreme estimates need to be identifiable, the key is seeing the spread along the extreme values. I hear you, you don't like it. I think its actually really good. If you are okay, we could let @jvcasillas be the judge and decide based on his preference?

**Comment by jvcasillas** [comment]
I'm ok with it. I think I would prefer it without the smallest/largest effect notation. Without reading the caption it won't be clear what the difference is between the dark and the grey. Perhaps if you alpha the grey a tad more and make the linerange a bit wider (wider for the raw than for the shrunken value) you won't need to dodge and it won't be too busy.

**Comment by troettge** [comment]
![image](https://user-images.githubusercontent.com/13022447/189702404-dd4a1401-6db9-4832-abc6-62e429f4ed38.png)
@jvcasillas good call on the thicker lines, also added title and subtitle. What y'all think?

**Comment by jvcasillas** [comment]
It's growing on me (though I still prefer different colors 😉). Can you do `lineend = "round"` on the raw estimates?

**Comment by troettge** [comment]
Different colors, rounded line heads @jvcasillas 
![meta_plot1_shrinkage](https://user-images.githubusercontent.com/13022447/189717536-aa69c8f6-8b93-49e3-b4a7-784f368b57da.png)

**Comment by jvcasillas** [comment]
I mean I guess I'm biased now, but that fucking shreds. 👍🏼 from me.

**Comment by troettge** [comment]
can you be convinced @stefanocoretta I think its pretty nice actually!

**Comment by stefanocoretta** [comment]
It's definitely better. Is the most recent code up?

**Comment by stefanocoretta** [comment]
I don't see the new version of the plot? Did you not save it perhaps?

**Comment by stefanocoretta** [comment]
Yes, the code was up to date but not the figure file. Now fixed.
