### ISSUE TITLE
Minutes - 2021/01/20

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#22]
## Action items

- [x] Port questionnaires to Google Forms (@jvcasillas, #8).
- [x] Continue work on RR draft (@stefanocoretta).
  - Made several edits, mostly in Step 4 section (still WIP).
- [x] Edit ExperimentalDetails.
  - Restructuring of sections.
  - Reformulation and extension.
- [x] Edit forking paths figure (@troettge).
- [x] Prepare `.bib` file for RR (@jvcasillas).
- [x] Prepare graphics for analysis workflow (all) to be given to teams as aid (#26).
- [x] Update OSF Data component (@stefanocoretta).
  - Started prepping of TextGrids.

## Discuss

- [x] RR
  - [x] 💡Idea: would be nice to use a measurement-error model also in the analysis-factors analysis, so that we don't just use a point-estimate of the deviation from the meta-analytical mean.
    - GO.
  - [x] How will we enter the demographic factors in the factors analysis since we have a score per individual rather than team?
    - [x] Averaging scores.
    - [x] Scale 1-100 belief.
  - [x] Help with summarising neuroscience, cognitive modeling, clinical, predictive models in RR.
    - Timo will do it @troettge.
  - [x] Discuss missing/ambiguous refs in RR
  - [x] Use of papaja in RR draft (#28).
- [x] Discuss [landing page](https://www.simplpoints.com/many-speech-analyses/) (Timo)
  - A few things should be highlighted: co-authorship, improving standards. 
- [x] Discuss analyst journey and experience (Timo)
  - In RR and landing page.
- [x] Materials
  - [x] Info on German determiner and adjective ending for prepping TextGrids.
- [x] Project management 
  - [x] GH project [Meetings](https://github.com/jvcasillas/many_analyses/projects/2).
  - [x] GH Actions (assign label `meetings` and project `Meetings` automatically if issue title contains "Minutes").
