### ISSUE TITLE
Minutes 2021-03-17

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#50]
### Action items

- [ ] RR [@stefanocoretta]
  - [x] Edit based on last meeting's discussion. 
  - [x] Update links.
  - [x] Edit `simulations.Rmd`.
  - [ ] References: parker et al (eco), summerfield, charles et al [@troettge @jvcasillas].
  - [ ] Info on consent form [@troettge].
- [x] ForkinPaths.png [@troettge]
  - Connect panels in A.
- [x]  Upload .svg versions of images. [@troettge]
- [x] Update peer-review survey (see #44 comments).
- [x] Update OSF [@troettge] #6
  - [x] Upload wav file to Data > production > audio.
- [x] Clean unused files on GDrive [@jvcasillas]
- [x] Prep list of terms to be discussed [@stefanocoretta]. #51 

### Discuss

- [x] Audio data. #6 
  - [x] eudat.eu
  - We will upload the audio data when the time comes to share them with the teams. In case reviewers will request to listen to them, we will share them directly.
- [x] Terms for models, demographic, analytic/al. See #51
  - What we have is fine, but we need to think of something better for "demographic" (this includes research expertise and prior belief). I will also make sure that there is consistency of use of analytic(al). 
- [x] Sample size justification.
  - We might leave it for now as is or hedge it like "we will aim at as many teams as possible, although we estimate a necessary minimum of 12" or the like. Or even we can take it out and just state that we will make sure to maximise number of teams or something.
- [x] Ask teams if they know about papers.
  - [x] Decide on when and where to ask.
  - At the end of the analyses and peer review.
- [x] PDFs of surveys instead of links to them?
  - We will upload pdf versions of the surveys to OSF and link to those in the RR.
- [x] Original "Blue bananas" study details to be included in the RR (as in related links/publications/other).
  - @troettge I'd like to be more explicit about the fact that the data comes from a prev study and was not designed for this one specifically. Is there any info that would help doing this?

**Comment by troettge** [comment]
@stefanocoretta @jvcasillas I added a procedure plot in figs. Check it out and lemme know.

**Comment by jvcasillas** [comment]
@troettge It looks pretty good. I like the idea of using the greyed pointer and dotted line to represent the mouse movement, but I barely caught it the first time. I wonder if changing the color of the pointer in the new position from black to something that stands out a bit more (red, for example) might help make that salient.

**Comment by stefanocoretta** [comment]
It looks wow! I think it would be better to spell out the captions a bit more, I had some trouble figuring out what they meant. This is a bit nit-picky, but the "confederate indicates ref" should be a separate step if we want to keep to the actual time line.

**Comment by troettge** [comment]
I suggest spelling out the details in the figure caption instead, I can number the different steps. Second point is obviously correct, BUT if considering it a separate step, we overall running into space issues. To more element, the smaller the elements  and the less readable they are. What do you say?

**Comment by troettge** [comment]
BUT I pushed a new version with slightly more descriptive captions, the confederate timeline being slightly offset to indicate the sequential nature of it and two icons indicating the two different agents involved.

**Comment by stefanocoretta** [comment]
I quite loik it!

**Comment by jvcasillas** [comment]
Update regarding survey links: qualtrics won't let me customize them, but I imagine that anywhere we need to put them we can customize them in html anchors. 

- Recruitment form: https://rutgers.ca1.qualtrics.com/jfe/form/SV_5nd1utFgq1uEPKm
- Analytical approach: https://rutgers.ca1.qualtrics.com/jfe/form/SV_3KreX0j6xDs2qDs
- Analytical survey: https://rutgers.ca1.qualtrics.com/jfe/form/SV_erqo54ElN7k71S6
- Intake form: https://rutgers.ca1.qualtrics.com/jfe/form/SV_1Fws3pQgaOGvtrw
- Peer review: https://rutgers.ca1.qualtrics.com/jfe/form/SV_3k5uG3oilQVMV5s

**Comment by troettge** [comment]
@stefanocoretta. "This study was preregistered on the 3rd of May 2018 (https://osf.io/c3kn7) and subsequently conducted by Simon Roessig, Michael Franke, and Timo Roettger for independent purposes (https://osf.io/tbjyv/). The research was never reported in a research presentation nor was it published." something like that?
